name: Get Gemini API key and N8N JWT Token

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Use secrets in a step
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Using Gemini API Key: $GEMINI_API_KEY"
          echo "Using JWT Secret: $JWT_SECRET"

      - name: Run a Node.js script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          node -e "
            console.log('Gemini API Key:', process.env.GEMINI_API_KEY);
            console.log('JWT Secret:', process.env.JWT_SECRET);
          "

      - name: Print Environment Variables
        run: printenv | sort
